# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmusic_api.proto\x12\tmusic_api\"\x16\n\x05Query\x12\r\n\x05query\x18\x01 \x01(\t\"\'\n\nArtistLink\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x99\x01\n\x05Track\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x18\n\x10\x64uration_seconds\x18\x04 \x01(\r\x12\r\n\x05\x61lbum\x18\x05 \x01(\t\x12\x11\n\talbum_url\x18\x06 \x01(\t\x12&\n\x07\x61rtists\x18\x07 \x03(\x0b\x32\x15.music_api.ArtistLink\"\xa7\x01\n\x05\x41lbum\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\r\x12\x18\n\x10\x64uration_seconds\x18\x05 \x01(\r\x12 \n\x06tracks\x18\x06 \x03(\x0b\x32\x10.music_api.Track\x12&\n\x07\x61rtists\x18\x07 \x03(\x0b\x32\x15.music_api.ArtistLink\")\n\x06\x41lbums\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.music_api.Album\"X\n\x06\x41rtist\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12 \n\x06\x61lbums\x18\x04 \x03(\x0b\x32\x10.music_api.Album\"+\n\x07\x41rtists\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.music_api.Artist2z\n\x08MusicApi\x12\x37\n\rSearchArtists\x12\x10.music_api.Query\x1a\x12.music_api.Artists\"\x00\x12\x35\n\x0cSearchAlbums\x12\x10.music_api.Query\x1a\x11.music_api.Albums\"\x00\x42\x30Z.github.com/emilia-miki/music-browser/music_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/emilia-miki/music-browser/music_api'
  _QUERY._serialized_start=30
  _QUERY._serialized_end=52
  _ARTISTLINK._serialized_start=54
  _ARTISTLINK._serialized_end=93
  _TRACK._serialized_start=96
  _TRACK._serialized_end=249
  _ALBUM._serialized_start=252
  _ALBUM._serialized_end=419
  _ALBUMS._serialized_start=421
  _ALBUMS._serialized_end=462
  _ARTIST._serialized_start=464
  _ARTIST._serialized_end=552
  _ARTISTS._serialized_start=554
  _ARTISTS._serialized_end=597
  _MUSICAPI._serialized_start=599
  _MUSICAPI._serialized_end=721
# @@protoc_insertion_point(module_scope)
